#########################################################################
# Title:            Sandbox: n8n-io                                     #
# Author(s):        JigSawFr                                            #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Remove legacy PostgreSQL Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"
  vars:
    var_prefix: "{{ n8n_name }}_postgres"

- name: Check legacy path
  ansible.builtin.stat:
    path: "{{ n8n_paths_location }}/app"
  register: stat_n8n_legacy_path

- name: "Import Postgres Role"
  ansible.builtin.include_role:
    name: postgres
  vars:
    postgres_instances: ["{{ n8n_postgres_name }}"]
    postgres_docker_env_db: "{{ n8n_postgres_docker_env_db }}"
    postgres_docker_image_tag: "{{ n8n_postgres_docker_image_tag }}"
    postgres_docker_image_repo: "{{ n8n_postgres_docker_image_repo }}"
    postgres_paths_folder: "{{ n8n_postgres_paths_folder }}"
    postgres_paths_location: "{{ n8n_postgres_paths_location }}"

- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Migrate n8n legacy directory
  migrate_folder:
    legacy_path: "{{ n8n_paths_location }}/app"
    new_path: "{{ n8n_paths_location }}/data/.n8n"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: '0775'
    recurse: false
  when: stat_n8n_legacy_path.stat.exists

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"
